# Generated by Django 6.0.4 on 2026-05-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'កំណត់ត្រាពន្ធ', 'verbose_name_plural': 'កំណត់ត្រាពន្ធ'},
        ),
        migrations.RemoveField(
            model_name='taxrecord',
            name='salary',
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='dependents',
            field=models.IntegerField(default=0, verbose_name='អ្នកអាស្រ័យ (នាក់)'),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='income',
            field=models.IntegerField(default=0, verbose_name='ចំណូលប្រចាំខែ (៛)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='net_income',
            field=models.IntegerField(default=0, verbose_name='ប្រាក់សុទ្ធ (៛)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='status',
            field=models.CharField(choices=[('single', 'នៅលីវ'), ('married', 'រៀបការ'), ('family', 'មានកូន')], default='single', max_length=10, verbose_name='ស្ថានភាពគ្រួសារ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_amount',
            field=models.IntegerField(verbose_name='ពន្ធប៉ាន់ស្មាន (៛)'),
        ),
    ]
