# Generated by Django 6.0.4 on 2026-05-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_taxrecord_options_remove_taxrecord_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrecord',
            name='property_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ប្រភេទអចលនទ្រព្យ'),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='property_value',
            field=models.IntegerField(blank=True, null=True, verbose_name='តម្លៃអចលនទ្រព្យ (៛)'),
        ),
        migrations.AddField(
            model_name='taxrecord',
            name='tax_type',
            field=models.CharField(choices=[('salary', 'ពន្ធលើប្រាក់បៀវតន៏'), ('property', 'ពន្ធអាក')], default='salary', max_length=10, verbose_name='ប្រភេទពន្ធ'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='dependents',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='អ្នកអាស្រ័យ (នាក់)'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='income',
            field=models.IntegerField(verbose_name='ចំណូល/តម្លៃអចលនទ្រព្យ (៛)'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='net_income',
            field=models.IntegerField(blank=True, null=True, verbose_name='ប្រាក់សុទ្ធ/តម្លៃសុទ្ធ (៛)'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='status',
            field=models.CharField(blank=True, choices=[('single', 'នៅលីវ'), ('married', 'រៀបការ'), ('family', 'មានកូន')], max_length=10, null=True, verbose_name='ស្ថានភាពគ្រួសារ'),
        ),
    ]
