# Generated by Django 6.0.4 on 2026-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_taxrecord_property_type_taxrecord_property_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrecord',
            name='currency',
            field=models.CharField(choices=[('KHR', '៛ រៀលកម្ពុជា'), ('USD', '$ ដុល្លារអាមេរិក')], default='KHR', max_length=3, verbose_name='រូបិយប័ណ្ណ'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ចំណូល/តម្លៃអចលនទ្រព្យ'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='net_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='ប្រាក់សុទ្ធ/តម្លៃសុទ្ធ'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='property_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='តម្លៃអចលនទ្រព្យ'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ពន្ធប៉ាន់ស្មាន'),
        ),
    ]
