# Generated by Django 5.2.1 on 2026-05-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_taxrecord_currency_alter_taxrecord_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrecord',
            name='wife_status',
            field=models.CharField(blank=True, choices=[('housework', 'ធ្វើការផ្ទះ'), ('working', 'ធ្វើការ')], default='housework', max_length=10, null=True, verbose_name='ស្ថានភាពប្រពន្ធ'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
