# Generated by Django 5.2.1 on 2026-05-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_taxrecord_wife_status_alter_taxrecord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCalculationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='អត្រាពន្ធ')),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='ចំនួនអាចពន្ធបាន')),
                ('deduction_children', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ការកាត់ពន្ធកូន')),
                ('deduction_wife', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ការកាត់ពន្ធប្រពន្ធ')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ការកាត់ពន្ធសរុប')),
                ('salary_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ពន្ធប្រាក់បៀវតន៏')),
                ('grant_benefit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='អត្ថប្រយោជន៍/អំណោយ')),
                ('grant_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ពន្ធលើអត្ថប្រយោជន៍')),
                ('base_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='អត្រាគោល')),
                ('property_type_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='គុណនាមប្រភេទអចលនទ្រព្យ')),
                ('progressive_multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='គុណនាមវឌ្ឍនភាព')),
                ('final_rate', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='អត្រាចុងក្រោយ')),
                ('tax_components', models.JSONField(default=dict, help_text='JSON object containing detailed tax calculation components', verbose_name='សមាសធាតុពន្ធ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ')),
                ('tax_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_details', to='calculator.taxrecord', verbose_name='កំណត់ត្រាពន្ធ')),
            ],
            options={
                'verbose_name': 'ព័ត៌មានលម្អិតនៃការគណនាពន្ធ',
                'verbose_name_plural': 'ព័ត៌មានលម្អិតនៃការគណនាពន្ធ',
            },
        ),
    ]
