# Generated by Django 5.2.1 on 2026-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_taxcalculationdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculationdetail',
            name='final_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='អត្រាចុងក្រោយ'),
        ),
    ]
