# Generated by Django 6.0.4 on 2026-05-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_taxcalculationdetail_final_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculationdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_type',
            field=models.CharField(choices=[('salary', 'ពន្ធលើប្រាក់បៀវតន៏'), ('property', 'ពន្ធអាក'), ('vat', 'ពន្ធតម្លៃបន្ថែម')], default='salary', max_length=10, verbose_name='ប្រភេទពន្ធ'),
        ),
    ]
