# Generated by Django 5.2.1 on 2026-05-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_alter_taxcalculationdetail_id_alter_taxrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_type',
            field=models.CharField(choices=[('salary', 'ពន្ធលើប្រាក់បៀវតន៏'), ('property', 'ពន្ធអាក'), ('vat', 'ពន្ធលើតម្លៃបន្ថែម')], default='salary', max_length=10, verbose_name='ប្រភេទពន្ធ'),
        ),
    ]
