# Generated by Django 6.0.4 on 2026-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_alter_taxrecord_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_type',
            field=models.CharField(choices=[('salary', 'ពន្ធលើប្រាក់បៀវតន៏'), ('property', 'ពន្ធអាក'), ('vat', 'ពន្ធលើតម្លៃបន្ថែម'), ('income', 'ពន្ធលើចំណូលលុយប្រតិបត្តិការ'), ('withholding', 'ពន្ធកាត់ទុក')], default='salary', max_length=15, verbose_name='ប្រភេទពន្ធ'),
        ),
    ]
