# Generated by Django 6.0.5 on 2026-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_alter_taxrecord_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_type',
            field=models.CharField(choices=[('salary', 'ពន្ធលើប្រាក់បៀវតន៏'), ('property', 'ពន្ធអាក'), ('vat', 'ពន្ធលើតម្លៃបន្ថែម'), ('income', 'ពន្ធលើចំណូលលុយប្រតិបត្តិការ'), ('withholding', 'ពន្ធកាត់ទុក'), ('patent', 'ពន្ធលើច្បាប់ផលិតម្ល'), ('special', 'ពន្ធលើកិច្ចការពិសេស'), ('registration', 'ពន្ធលើការចុះបញ្ជី'), ('unused_land', 'ពន្ធលើដីដែលមិនប្រើប្រាស់'), ('accomodation', 'ពន្ធលើការស្នាក់នៅ')], default='salary', max_length=15, verbose_name='ប្រភេទពន្ធ'),
        ),
    ]
