# Generated by Django 6.0.5 on 2026-05-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_alter_taxrecord_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcalculationdetail',
            name='salary_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='ពន្ធប្រាក់បៀវត្ស'),
        ),
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_type',
            field=models.CharField(choices=[('salary', 'ពន្ធលើប្រាក់បៀវត្ស'), ('property', 'ពន្ធអាករ'), ('vat', 'អាករលើតម្លៃបន្ថែម'), ('income', 'ពន្ធលើចំណូលលុយប្រតិបត្តិការ'), ('withholding', 'ពន្ធកាត់ទុក'), ('patent', 'ពន្ធលើប៉ាតង់'), ('special', 'អាករពិសេស'), ('registration', 'ពន្ធប្រថាប់ត្រា'), ('unused_land', 'ពន្ធលើដីធ្លីមិនបានប្រើប្រាស់'), ('accomodation', 'ពន្ធលើការស្នាក់នៅ')], default='salary', max_length=15, verbose_name='ប្រភេទពន្ធ'),
        ),
    ]
