# Generated by Django 6.0.5 on 2026-05-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0013_alter_taxcalculationdetail_salary_tax_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_type',
            field=models.CharField(choices=[('salary', 'ពន្ធលើប្រាក់បៀវត្ស'), ('property', 'ពន្ធអាករ'), ('vat', 'អាករលើតម្លៃបន្ថែម'), ('income', 'ពន្ធលើចំណូលលុយប្រតិបត្តិការ'), ('withholding', 'ពន្ធលើថ្លៃឈ្នួលអចលនទ្រព្យ'), ('patent', 'ពន្ធលើប៉ាតង់'), ('special', 'អាករពិសេស'), ('registration', 'ពន្ធប្រថាប់ត្រា'), ('unused_land', 'ពន្ធលើដីធ្លីមិនបានប្រើប្រាស់'), ('accomodation', 'ពន្ធលើការស្នាក់នៅ'), ('advertising', 'Tax on advertising boards')], default='salary', max_length=15, verbose_name='ប្រភេទពន្ធ'),
        ),
    ]
